### ISSUE TITLE
SetWindowToWallRatioByFacade tests

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/openstudio-model-articulation-gem#21]
@DavidGoldwasser I tested this with the --run_tests call.  Does this use openstudio-standards in the CLI or does it use local openstudio-standards?

Only the SetWindowToWallRatioByFacade measure test is failing.

It appears that the three tests that use:
```
    output_dir = File.expand_path('output', File.dirname(__FILE__))
    FileUtils.mkdir output_dir unless Dir.exist? output_dir
```

Are overriding other test files or somehow interfering with other tests in the test script.  Using the format of other tests fixes the problem.

**Comment by DavidGoldwasser** [comment]
@mdahlhausen that uses standards in the CLI, but you can run rake task to call measure testing gem directly using your system ruby and its version of standards. (except for sizing run in measure which ends up using CLI). I'll run local test later and see if I can re-produce the error on my checkout or the online CI system.

**Comment by DavidGoldwasser** [comment]
On windows I noticed a non-deterministic failure on a test for this, maybe split door, I'll document it next time I see it. I expect it is related to geometry library.
