### ISSUE TITLE
3.1.0 upgrade issues

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-model-articulation-gem#34]
Here are results with 9/18 installer run locally on mac with `openstudio measure -r`
<img width="411" alt="Screen Shot 2020-09-20 at 11 49 12 PM" src="https://user-images.githubusercontent.com/4857055/93735967-f65cc900-fb9b-11ea-99a7-96039818c556.png">

Only 6 measures account for the 52 failures and 23 errors. These are all variations of prototype, baseline, and create_typical measures. Note space type wizard and create_bar measures do not have any failures or errors.

I'll add comments below providing information on the errors

cc: @mdahlhausen

**Comment by DavidGoldwasser** [comment]
create_typical_doe_building_from_model small_office failure cause. At first glance looking at stdout-energyplus for the other 4 failures they may have similar cuase

From openstuido-standards.log
ERROR Stat file: :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/weather/../../../data/weather/USA_FL_Tampa-MacDill.AFB.747880_TMY3.stat was not found when calculating ground temperatures.
WARN  Could not find ground temperatures in stat file; will use standards lookup.

ERROR Results for the run couldn't be found here: /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/tests/output/small_office/SR1/run/eplusout.sql.

From run.log
[23:38:14.533435 ERROR] :/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/util/energyplus.rb failed with EnergyPlus failed and did not create an eplusout.end file. Check the stdout-energyplus log., :/ruby/2.5.0/gems/openstudio-workflow-2.0.1/lib/openstudio/workflow/util/energyplus.rb:200:in `call_energyplus'

From stdout-energyplus
**FATAL:DLL problem cause program termination
libc++abi.dylib: terminating with uncaught exception of type EnergyPlus::FatalError: DLL problem cause program termination

**Comment by DavidGoldwasser** [comment]
create_typical_doe_building_from_model large_office error cause. the other error, test_pfp_boxes, may have similar cause.

Error occurs after successful sizing run. Message below is form console of measure test:
[openstudio.weather.Model] <1> Stat file: :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/weather/../../../data/weather/USA_CO_Denver-Aurora-Buckley.AFB.724695_TMY3.stat was not found when calculating ground temperatures.
[openstudio.weather.Model] <1> Could not find .ddy file for: /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/tests/USA_TX_Houston-Bush.Intercontinental.AP.722430_TMY3.ddy.
Could not find .ddy file for: /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/tests/USA_TX_Houston-Bush.Intercontinental.AP.722430_TMY3.ddy.
E

Finished in 6.622440s, 0.1510 runs/s, 0.4530 assertions/s.

  1) Error:
CreateTypicalDOEBuildingFromModel_Test#test_large_office. May be related to `ArgumentError: comparison of FalseClass with 20 failed
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:417:in `model_add_cw_loop'`

ArgumentError: comparison of FalseClass with 20 failed
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:417:in `model_add_cw_loop'
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:5479:in `model_get_or_add_chilled_water_loop'
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:6037:in `model_add_hvac_system'
    :/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension/core/os_lib_model_generation.rb:2975:in `block (2 levels) in typical_building_from_model'
    :/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension/core/os_lib_model_generation.rb:2961:in `each'
    :/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension/core/os_lib_model_generation.rb:2961:in `block in typical_building_from_model'
    :/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension/core/os_lib_model_generation.rb:2934:in `each'
    :/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension/core/os_lib_model_generation.rb:2934:in `typical_building_from_model'
    /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/measure.rb:473:in `run'
    /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/tests/create_typical_doe_building_from_model_test.rb:107:in `apply_measure_to_model'
    /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_typical_doe_building_from_model/tests/create_typical_doe_building_from_model_test.rb:161:in `test_large_office'

**Comment by DavidGoldwasser** [comment]
**create_DOE_prototype_building**. Both tests have similar failures, no indication as to why create_models failed, no output files with additional details:

CreateDOEPrototypeBuildingTest#test_primary_school [/Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_DOE_prototype_building/tests/create_DOE_prototype_building_test.rb:159]:
FAILURES: Error - PrimarySchool-90.1-2004-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-90.1-2007-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-90.1-2010-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-DOE Ref 1980-2004-ASHRAE 169-2013-3A - Model was not created successfully.
Error - PrimarySchool-DOE Ref Pre-1980-ASHRAE 169-2013-3A - Model was not created successfully.

**Comment by DavidGoldwasser** [comment]
**create_baseline_building** 2013 and 2007 template see this error, Prototype.hvac_systems.rb:417 is also where create_typical errors are

ArgumentError: comparison of FalseClass with 20 failed
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:417:in `model_add_cw_loop'

[utilities.geometry.join] <1> Union has inner loops
[utilities.geometry.join] <1> Union has inner loops
[utilities.geometry.join] <1> Union has inner loops
[utilities.geometry.join] <1> Union has inner loops
[utilities.geometry.joinAll] <1> Could not join all connected components
[openstudio.weather.Model] <1> Could not find .ddy file for: /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_baseline_building/tests/USA_TX_Houston-Bush.Intercontinental.AP.722430_TMY3.ddy.
Could not find .ddy file for: /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_baseline_building/tests/USA_TX_Houston-Bush.Intercontinental.AP.722430_TMY3.ddy.
E

Finished in 11.728314s, 0.0853 runs/s, 0.5116 assertions/s.

  1) Error:
CreateBaselineBuildingTest#test_901_2013_sec_school:
ArgumentError: comparison of FalseClass with 20 failed
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/prototypes/common/objects/Prototype.hvac_systems.rb:417:in `model_add_cw_loop'
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/standards/Standards.Model.rb:1017:in `model_add_prm_baseline_system'
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/standards/Standards.Model.rb:119:in `block in model_create_prm_baseline_building'
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/standards/Standards.Model.rb:100:in `each'
    :/ruby/2.5.0/bundler/gems/openstudio-standards-b0cabd8c2fa8/lib/openstudio-standards/standards/Standards.Model.rb:100:in `model_create_prm_baseline_building'
    /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_baseline_building/measure.rb:229:in `run'
    /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_baseline_building/tests/create_baseline_building_test.rb:95:in `apply_measure_to_model'
    /Users/dgoldwas/Documents/GitHub/URBANopt/openstudio-model-articulation-gem/lib/measures/create_baseline_building/tests/create_baseline_building_test.rb:108:in `test_901_2013_sec_school'

**Comment by DavidGoldwasser** [comment]
**create_baseline_building** 2010 failed sizing run SRVLT with similar error to create_typical small office. Below is the content of stdout-energyplus:

**FATAL:DLL problem cause program termination
libc++abi.dylib: terminating with uncaught exception of type EnergyPlus::FatalError: DLL problem cause program termination

**Comment by DavidGoldwasser** [comment]
Minor issue for another time, create_prototype_building create_baseline_building writes output to top level of repo not inside measure. Should be inside measure test directory, would create more issues if measure tests run in parallel.

**Comment by DavidGoldwasser** [comment]
radiant_slab_with_doas was failing tests in common measure gem. That measure belongs in articulation anyway, so moved it here. 

- [ ] Errors may go away with updated standards gem but I need to confirm that.

**Comment by mdahlhausen** [comment]
@DavidGoldwasser I pushed a fix for radiant_slab_with_doas on the common measures gem repo.  I guess you can move that here.  It's related to the same SQL errors that are causing the other measures to fail.

**Comment by DavidGoldwasser** [comment]
10/12 updates with rc3. 33 failures across 3 measures.

create_typical_doe_building_from_model 2 failures

- [ ] (midrise_apartment,generic_gbxml) - [openstudio.model.ElectricEquipmentDefinition] Latent Fraction and Radiant Fraction sum to 0.5 and you supplied a Lost Fraction of 1 which would result in a sum greater than 1.0
